// language.js
// This file contains a comprehensive list of language codes and their corresponding names.
// This data is used to dynamically populate the language selection dropdowns in the web application.
const languages = {
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  pt: "Portuguese",
  ru: "Russian",
  zh: "Chinese (Simplified)",
  ja: "Japanese",
  ko: "Korean",
  ar: "Arabic",
  hi: "Hindi",
  bn: "Bengali",
  ur: "Urdu",
  tr: "Turkish",
  nl: "Dutch",
  sv: "Swedish",
  no: "Norwegian",
  da: "Danish",
  fi: "Finnish",
  pl: "Polish",
  cs: "Czech",
  hu: "Hungarian",
  el: "Greek",
  th: "Thai",
  vi: "Vietnamese",
  id: "Indonesian",
  ms: "Malay",
  tl: "Tagalog",
  fa: "Persian",
  he: "Hebrew",
  uk: "Ukrainian",
  ro: "Romanian",
  bg: "Bulgarian",
  sr: "Serbian",
  hr: "Croatian",
  sk: "Slovak",
  sl: "Slovenian",
  et: "Estonian",
  lv: "Latvian",
  lt: "Lithuanian",
  sq: "Albanian",
  mk: "Macedonian",
  is: "Icelandic",
  ga: "Irish",
  cy: "Welsh",
  mt: "Maltese",
  ka: "Georgian",
  az: "Azerbaijani",
  am: "Amharic",
  sw: "Swahili",
  yo: "Yoruba",
  zu: "Zulu",
  ha: "Hausa",
  ig: "Igbo",
  km: "Khmer",
  lo: "Lao",
  my: "Burmese",
  ne: "Nepali",
  si: "Sinhala",
  ta: "Tamil",
  te: "Telugu",
  kn: "Kannada",
  ml: "Malayalam",
  gu: "Gujarati",
  pa: "Punjabi",
  or: "Odia",
  as: "Assamese",
  sd: "Sindhi",
  ug: "Uyghur",
  uz: "Uzbek",
  kk: "Kazakh",
  ky: "Kyrgyz",
  tg: "Tajik",
  tk: "Turkmen",
  mn: "Mongolian",
  dz: "Dzongkha",
  bo: "Tibetan",
  dv: "Dhivehi",
  fj: "Fijian",
  sm: "Samoan",
  to: "Tongan",
  mi: "Maori",
  haw: "Hawaiian",
  ht: "Haitian Creole",
  mg: "Malagasy",
  ny: "Chichewa",
  sn: "Shona",
  st: "Sesotho",
  ts: "Tsonga",
  xh: "Xhosa",
  bi: "Bislama",
  ch: "Chamorro",
  ty: "Tahitian",
  wo: "Wolof",
  ff: "Fulah",
  ln: "Lingala",
  lu: "Luba-Katanga",
  kg: "Kongo",
  rw: "Kinyarwanda",
  sg: "Sango",
  so: "Somali",
  ti: "Tigrinya",
  ve: "Venda",
  tn: "Tswana",
  ss: "Swati",
  nr: "Ndebele (South)",
  nd: "Ndebele (North)",
  om: "Oromo",
  gd: "Scottish Gaelic",
  gv: "Manx",
  kw: "Cornish",
  fo: "Faroese",
  li: "Limburgish",
  wa: "Walloon",
  co: "Corsican",
  sc: "Sardinian",
  eu: "Basque",
  gl: "Galician",
  ca: "Catalan",
  an: "Aragonese",
  oc: "Occitan",
  br: "Breton",
  fy: "Western Frisian",
  gaa: "Ga",
  ee: "Ewe",
  ak: "Akan",
  ig: "Igbo",
  bm: "Bambara",
  ff: "Fula",
  kr: "Kanuri",
  lg: "Ganda",
  rn: "Rundi",
  sg: "Sango",
  sn: "Shona",
  st: "Southern Sotho",
  tn: "Tswana",
  ts: "Tsonga",
  ve: "Venda",
  xh: "Xhosa",
  zu: "Zulu",
  tw: "Twi",
  ln: "Lingala",
  lu: "Luba-Katanga",
  mg: "Malagasy",
  ny: "Chichewa",
  qu: "Quechua",
  gn: "Guarani",
  ay: "Aymara",
  kj: "Kuanyama",
  na: "Nauru",
  nr: "Ndebele (South)",
  oj: "Ojibwa",
  pi: "Pali",
  rm: "Romansh",
  se: "Northern Sami",
  sm: "Samoan",
  ty: "Tahitian",
  vo: "Volapük",
  wa: "Walloon",
  za: "Zhuang",
  ii: "Sichuan Yi",
  ug: "Uyghur",
  dz: "Dzongkha",
  bo: "Tibetan",
  dv: "Dhivehi",
  iu: "Inuktitut",
  ik: "Inupiaq",
  kl: "Kalaallisut",
  kr: "Kanuri",
  ng: "Ndonga",
  nr: "South Ndebele",
  ss: "Swati",
  tn: "Tswana",
  ts: "Tsonga",
  ve: "Venda",
  xh: "Xhosa",
  zu: "Zulu",
  ab: "Abkhazian",
  av: "Avaric",
  ba: "Bashkir",
  be: "Belarusian",
  ce: "Chechen",
  cv: "Chuvash",
  os: "Ossetic",
  tt: "Tatar",
  udm: "Udmurt",
  myv: "Erzya",
  mdf: "Moksha",
  kv: "Komi",
  krc: "Karachay-Balkar",
  lez: "Lezghian",
  alt: "Southern Altai",
  sah: "Sakha",
  tyv: "Tuvan",
  cv: "Chuvash",
  bxr: "Buryat",
  xal: "Kalmyk",
  kbd: "Kabardian",
  ady: "Adyghe",
  inh: "Ingush",
  che: "Chechen",
  dar: "Dargwa",
  lbe: "Lak",
  tab: "Tabassaran",
  ava: "Avar",
  lez: "Lezghian",
  rut: "Rutul",
  agx: "Aghul",
  udi: "Udi",
  krc: "Karachay-Balkar",
  kum: "Kumyk",
  nog: "Nogai",
  gag: "Gagauz",
  tkr: "Tsakhur",
  abk: "Abkhazian",
  ady: "Adyghe",
  kbd: "Kabardian",
  ceb: "Cebuano",
  ilo: "Iloko",
  pam: "Pampanga",
  bcl: "Bikol",
  hil: "Hiligaynon",
  war: "Waray",
  mrw: "Maranao",
  mag: "Maguindanao",
  tsg: "Tausug",
  chv: "Chavacano",
  pag: "Pangasinan",
  bik: "Bikol",
  ceb: "Cebuano",
  hil: "Hiligaynon",
  ilo: "Iloko",
  pam: "Pampanga",
  war: "Waray-Waray",
  "zh-TW": "Chinese (Traditional)",
  "zh-CN": "Chinese (Simplified)",
  yue: "Cantonese",
  min: "Min Nan",
  hak: "Hakka",
  wuu: "Wu Chinese",
  cmn: "Mandarin Chinese",
  gan: "Gan Chinese",
  hsn: "Xiang Chinese",
  jpn: "Japanese",
  kor: "Korean",
  vie: "Vietnamese",
  tha: "Thai",
  khm: "Khmer",
  lao: "Lao",
  mya: "Burmese",
  ind: "Indonesian",
  msa: "Malay (Standard)",
  tgl: "Tagalog",
  fas: "Persian",
  heb: "Hebrew",
  ukr: "Ukrainian",
  ron: "Romanian",
  bul: "Bulgarian",
  srp: "Serbian",
  hrv: "Croatian",
  slk: "Slovak",
  slv: "Slovenian",
  est: "Estonian",
  lav: "Latvian",
  lit: "Lithuanian",
  sqi: "Albanian",
  mkd: "Macedonian",
  isl: "Icelandic",
  gle: "Irish",
  cym: "Welsh",
  mlt: "Maltese",
  kat: "Georgian",
  aze: "Azerbaijani",
  amh: "Amharic",
  swa: "Swahili",
  yor: "Yoruba",
  zul: "Zulu",
  hau: "Hausa",
  ibo: "Igbo",
  kin: "Kinyarwanda",
  run: "Rundi",
  nya: "Chichewa",
  sna: "Shona",
  sot: "Southern Sotho",
  tso: "Tsonga",
  ven: "Venda",
  xho: "Xhosa",
  bos: "Bosnian",
  mri: "Maori",
  hye: "Armenian",
  geo: "Georgian",
  amh: "Amharic",
  tir: "Tigrinya",
  som: "Somali",
  orm: "Oromo",
  snd: "Sindhi",
  syr: "Syriac",
  tgk: "Tajik",
  tkm: "Turkmen",
  uig: "Uyghur",
  uzb: "Uzbek",
  kaz: "Kazakh",
  kir: "Kyrgyz",
  mon: "Mongolian",
  dzo: "Dzongkha",
  bod: "Tibetan",
  div: "Dhivehi",
  fao: "Faroese",
  gla: "Scottish Gaelic",
  glv: "Manx",
  cor: "Cornish",
  fry: "Western Frisian",
  eus: "Basque",
  glg: "Galician",
  cat: "Catalan",
  arg: "Aragonese",
  oci: "Occitan",
  bre: "Breton",
  lim: "Limburgish",
  wln: "Walloon",
  cos: "Corsican",
  srd: "Sardinian",
  chr: "Cherokee",
  cho: "Choctaw",
  nav: "Navajo",
  moh: "Mohawk",
  ojb: "Ojibwa",
  cre: "Cree",
  iku: "Inuktitut",
  kal: "Kalaallisut",
  bin: "Bini",
  fon: "Fon",
  gaa: "Ga",
  kpe: "Kpelle",
  lom: "Loma",
  men: "Mende",
  mfe: "Morisyen",
  nqo: "N'Ko",
  run: "Rundi",
  sna: "Shona",
  sot: "Southern Sotho",
  ssw: "Swati",
  tso: "Tsonga",
  ven: "Venda",
  xho: "Xhosa",
  yid: "Yiddish",
  syr: "Syriac",
  arc: "Aramaic",
  grc: "Ancient Greek",
  lat: "Latin",
  san: "Sanskrit",
  pli: "Pali",
  ave: "Avestan",
  chu: "Old Church Slavonic",
  sga: "Old Irish",
  goh: "Old High German",
  non: "Old Norse",
  ang: "Old English",
  fro: "Old French",
  pro: "Old Provençal",
  syc: "Classical Syriac",
  cop: "Coptic",
  egy: "Ancient Egyptian",
  akk: "Akkadian",
  sux: "Sumerian",
  hit: "Hittite",
  uga: "Ugaritic",
  phn: "Phoenician",
  arc: "Aramaic",
  pal: "Pahlavi",
  peo: "Old Persian",
  xho: "Xhosa",
  zul: "Zulu",
  nbl: "Southern Ndebele",
  nso: "Northern Sotho",
  ssw: "Swati",
  tso: "Tsonga",
  ven: "Venda",
  tsn: "Tswana",
};
